### ISSUE TITLE
Missing functions and objects in notebook 4

### ISSUE THREAD

**Issue by jeremylhour** [aws/sagemaker-jumpstart-industry-pack#48]
Hi, 

I'm trying to run the lines of code in: https://github.com/aws/sagemaker-jumpstart-industry-pack/blob/main/docs/source/notebooks/finance/notebook4/SEC_10K_10Q_8K_section_extraction.rst

However, I miss the function "get_form_items" and the objects "columns_10K" and "header_mappings_10K", in the following block 
https://github.com/aws/sagemaker-jumpstart-industry-pack/blob/203530c674dad6dbb6f586fa03cf319efd7b17a5/docs/source/notebooks/finance/notebook4/SEC_10K_10Q_8K_section_extraction.rst#L356

I could not find these objects in the package either. Any help appreciated.

**Comment by firmai** [comment]
Did you end up finding it?
